### ISSUE TITLE
Small Typo in Readme

### ISSUE THREAD

**Issue by bennyguitar** [Objective-Cloud/OCFWebServer#1]
Under **Example:Forms**, there is a missing opening ( in the first method's <code>respondWith</code> block.

I didn't feel like this warranted a pull request, just wanted to let you guys/gals know. BTW, awesome project. I've forked it and am working directly with some PostgreSQL queries/handling.

**Comment by Objective-Cloud** [comment]
Thanks for reporting. 

https://github.com/Objective-Cloud/OCFWebServer/commit/5d80b357dbbebb8f1da2d81c25b3a132fea84111

Fixed. You may also want to look at OCFWeb ( https://github.com/Objective-Cloud/OCFWeb ) which is a wrapper around OCFWebServer.
